import os
import re
import subprocess
import ollama

# --- CONFIGURATION ---
REPO_PATH = os.path.dirname(os.path.abspath(__file__))
MODEL_NAME = "gemma4:e2b"                     # Using your installed Gemma 4 model

# --- GIT UTILITIES ---
def execute_git_pipeline():
    """Stages, commits, and pushes to remote repository silently via SSH."""
    try:
        os.chdir(REPO_PATH)
        subprocess.run(["git", "add", "."], check=True, capture_output=True)
        
        # Check if there are actual changes to commit
        status = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
        if not status.stdout.strip():
            print("💤 No new code changes generated by the agent this round.")
            return

        commit_msg = "feat(autonomous): code generated and synchronized by Gemma-4 agent"
        subprocess.run(["git", "commit", "-m", commit_msg], check=True, capture_output=True)
        subprocess.run(["git", "push", "origin", "main"], check=True, capture_output=True)
        print("🚀 Code pushed to GitHub successfully!")
    except subprocess.CalledProcessError as e:
        print(f"❌ Git pipeline error: {e.stderr.decode() if e.stderr else e}")

# --- SYSTEM EXECUTION CHECKERS ---
def compile_and_test():
    """Runs tests before allowing a Git push to prevent broken commits."""
    print("🧪 Running local builds and compiler verification...")
    try:
        os.chdir(REPO_PATH)
        # Optional: Run hardhat tests to make sure smart contracts compile properly
        if os.path.exists(os.path.join(REPO_PATH, "contracts")):
            subprocess.run("npm run test:contracts", check=True, capture_output=True, shell=True)
        return True
    except subprocess.CalledProcessError:
        print("⚠️ Code validation failed. Skipping Git deployment to safeguard main branch.")
        return False

# --- CODE WRITER LOGIC ---
def parse_and_write_files(ai_response):
    """Parses special block formats to extract multiple target files from monorepo instructions."""
    # Pattern looks for: [FILE: path/to/file.ext] ...code... [END_FILE]
    file_blocks = re.findall(r'\[FILE:\s*(.*?)\](.*?)\[END_FILE\]', ai_response, re.DOTALL)
    
    if not file_blocks:
        print("❌ AI response format missing file block demarcations.")
        return False

    for rel_path, code in file_blocks:
        clean_path = rel_path.strip()
        full_dest_path = os.path.join(REPO_PATH, clean_path)
        
        # Ensure directories exist for the specific app layer
        os.makedirs(os.path.dirname(full_dest_path), exist_ok=True)
        
        with open(full_dest_path, "w", encoding="utf-8") as f:
            f.write(code.strip())
        print(f"💾 File updated: {clean_path}")
    return True

# --- MAIN AGENT LOOP ---
def run_autonomous_agent(task_prompt):
    tech_context = """
    You are an absolute autonomous system developer for 'TrustLance', a production Web3 monorepo.
    Architecture Context:
    - /contracts : Solidity ^0.8.20, Hardhat, OpenZeppelin. Uses Withdrawal pattern.
    - /backend : Node.js, Express, Prisma (PostgreSQL), Redis.
    - /frontend : Next.js App Router, Tailwind CSS, Wagmi/RainbowKit.

    Output format instructions:
    You are allowed to write or modify multiple files. Wrap EVERY file configuration cleanly like this:
    [FILE: contracts/Escrow.sol]
    // code here
    [END_FILE]
    
    Do not add conversational text or markdown around the blocks. Go straight to outputting files.
    """
    
    print(f"🤖 Gemma-4 thinking and coding your request...")
    # Injecting the <|think|> prompt wrapper for Gemma 4's deeper reasoning mode
    response = ollama.generate(
        model=MODEL_NAME,
        system=f"<|think|>\n{tech_context}",
        prompt=task_prompt
    )
    
    raw_output = response['response']
    
    if parse_and_write_files(raw_output):
        if compile_and_test():
            execute_git_pipeline()

if __name__ == "__main__":
    # Input your uninterrupted development goal here
    TARGET_GOAL = "Create the foundational Escrow smart contract inside the contracts directory tracking milestone states (Created, Locked, Released, Disputed)."
    run_autonomous_agent(TARGET_GOAL)
