// This file represents the structure built by Prisma. We need a seed for testing visibility.
-- In a real setup, this is generated by 'npx prisma migrate dev' or similar CLI commands.
// For simulation, we assume data can be inserted.

[FILE: backend/seed.ts]
import { PrismaClient } from '@prisma/client';
import { faker } from '@faker-js/faker';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding Hiring Opportunities...');

  const opportunities = [];
  for (let i = 0; i < 10; i++) {
    opportunities.push({
      title: faker.commerce.productName(),
      description: faker.lorem.sentence(),
      location: faker.location.city(),
      salary: parseFloat(faker.number.float({ min: 50000, max: 150000 })),
      postedAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000), // Posted in the last 30 days
      isPublic: true,
    });
  }

  await prisma.hiringOpportunity.createMany({
    data: opportunities,
  });

  console.log(`Successfully seeded ${opportunities.length} hiring opportunities.`);
}

main()
  .catch(e => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });